title: co-gy's blog
description: ~ ~ ~
theme: minima
url: https://co-gy.github.io/
author: co-gy
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - about.md

minima:
  skin: solarized
  social_links:
    - { platform: github,  user_url: "https://github.com/co-py" }

show_excerpts: true

include: 
  - _pages