title: co-gy's blog
description: ~ ~ ~
theme: minima
url: https://co-gy.github.io/
author: co-gy
plugins:
  - jekyll-feed

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/co-py" }

author:
  name: co-py
  email: "gyc5529@gmail.com"