title: co-gy's blog
description: ~ ~ ~
remote_theme: jekyll/minima
url: https://co-gy.github.io/
author: co-gy
plugins:
  # - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true

header_pages:
  - about.md

minima:
  skin: classic
  social_links:
    - { platform: github,  user_url: "https://github.com/co-py" }

show_excerpts: true
